/*
=====================================================
勤怠管理システム
create_tables.sql

作成者：森・庄山
DB：PostgreSQL

このSQLは勤怠管理システムで使用する
全テーブルを作成するSQLです。
=====================================================
*/

/*
=====================================================
users テーブル

利用者・管理者の情報を保存するテーブル

ログインや権限判定などで使用する。
=====================================================
*/
CREATE TABLE users (

    -- ユーザーID（主キー）
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- 社員番号
    employee_number VARCHAR(20) NOT NULL,

    -- 氏名
    name VARCHAR(50) NOT NULL,

    -- パスワード
    password VARCHAR(255) NOT NULL,

    -- 権限
    -- USER : 一般利用者
    -- ADMIN : 管理者
    role VARCHAR(20)
        NOT NULL
        DEFAULT 'USER',

    -- 登録日時
    created_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    -- 更新日時
    updated_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    /*
    ==========================
    制約
    ==========================
    */

    -- 主キー
    CONSTRAINT pk_users
        PRIMARY KEY (user_id),

    -- 社員番号は重複不可
    CONSTRAINT uq_users_employee_number
        UNIQUE (employee_number),

    -- roleはUSERかADMINのみ
    CONSTRAINT ck_users_role
        CHECK (
            role IN ('USER', 'ADMIN')
        )

);

/*
=====================================================
attendances テーブル

利用者ごとの出勤・退勤など、
1日単位の勤怠情報を保存するテーブル。

主な用途：
・出勤時刻の保存
・退勤時刻の保存
・休憩時間の保存
・実働時間の保存
・現在の勤務状態の管理
=====================================================
*/
CREATE TABLE attendances (

    /*
    勤怠ID（主キー）

    勤怠データを1件ずつ識別するための番号。
    PostgreSQLが1、2、3……と自動で番号を付ける。
    */
    attendance_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    /*
    ユーザーID（外部キー）

    この勤怠データが、どの利用者のものかを表す。
    usersテーブルのuser_idにつながる。
    */
    user_id BIGINT
        NOT NULL,

    /*
    勤務日

    どの日の勤怠情報なのかを保存する。
    DATE型なので、時刻は含まない。

    保存例：
    2026-08-03
    */
    work_date DATE
        NOT NULL,

    /*
    出勤日時

    利用者が出勤ボタンを押した日時を保存する。

    出勤前はまだ値が存在しないため、
    NULLを許可している。

    保存例：
    2026-08-03 09:00:00
    */
    clock_in_at TIMESTAMP,

    /*
    退勤日時

    利用者が退勤ボタンを押した日時を保存する。

    出勤中はまだ退勤していないため、
    NULLを許可している。

    保存例：
    2026-08-03 18:00:00
    */
    clock_out_at TIMESTAMP,

    /*
    休憩時間（分）

    休憩時間を「分」で保存する。

    例：
    60分休憩 → 60
    90分休憩 → 90

    値が指定されていない場合は0が入る。
    */
    break_minutes INTEGER
        NOT NULL
        DEFAULT 0,

    /*
    実働時間（分）

    退勤時刻から出勤時刻と休憩時間を引いた結果を
    分単位で保存する。

    計算例：
    09:00～18:00 ＝ 540分
    540分－休憩60分 ＝ 実働480分

    退勤前は計算できないため、NULLを許可している。
    */
    working_minutes INTEGER,

    /*
    勤怠状態

    現在の勤怠状況を保存する。

    NOT_STARTED：未出勤
    WORKING    ：勤務中
    FINISHED   ：退勤済み

    初期値はNOT_STARTED。
    */
    attendance_status VARCHAR(20)
        NOT NULL
        DEFAULT 'NOT_STARTED',

    /*
    備考

    勤怠に関する補足情報を保存する。

    例：
    ・電車遅延
    ・直行直帰
    ・体調不良による早退

    入力しないこともあるため、NULLを許可している。
    */
    note VARCHAR(255),

    /*
    作成日時

    この勤怠データが作成された日時。
    INSERT時に現在日時が自動で保存される。
    */
    created_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    /*
    更新日時

    この勤怠データを最後に更新した日時。

    PostgreSQLではMySQLの
    ON UPDATE CURRENT_TIMESTAMPが使えないため、
    更新時はJava側で現在日時を設定する。
    */
    updated_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,


    /*
    =====================================================
    ここからattendancesテーブルの制約
    =====================================================
    */

    /*
    attendance_idを主キーに設定する。

    主キーには、
    ・NULL不可
    ・重複不可
    というルールが自動で付く。
    */
    CONSTRAINT pk_attendances
        PRIMARY KEY (attendance_id),

    /*
    user_idを外部キーに設定する。

    attendances.user_idには、
    usersテーブルに実在するuser_idだけを登録できる。
    */
    CONSTRAINT fk_attendances_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE RESTRICT,

    /*
    同じ利用者について、同じ勤務日の勤怠を
    2件以上登録できないようにする。

    例：
    user_id = 1、work_date = 2026-08-03
    の組み合わせは1件だけ。
    */
    CONSTRAINT uq_attendances_user_work_date
        UNIQUE (user_id, work_date),

    /*
    休憩時間にマイナスの値が入ることを禁止する。

    OK：0、30、60、90
    NG：-30、-60
    */
    CONSTRAINT ck_attendances_break_minutes
        CHECK (break_minutes >= 0),

    /*
    実働時間にマイナスの値が入ることを禁止する。

    退勤前のNULLは許可する。
    値が入る場合は0以上でなければならない。
    */
    CONSTRAINT ck_attendances_working_minutes
        CHECK (
            working_minutes IS NULL
            OR working_minutes >= 0
        ),

    /*
    attendance_statusに登録できる値を制限する。

    次の3種類以外は登録できない。
    ・NOT_STARTED
    ・WORKING
    ・FINISHED
    */
    CONSTRAINT ck_attendances_status
        CHECK (
            attendance_status IN (
                'NOT_STARTED',
                'WORKING',
                'FINISHED'
            )
        ),

    /*
    退勤日時が出勤日時より前になることを禁止する。

    出勤前や退勤前はNULLが入るため、
    どちらかがNULLの場合はエラーにしない。

    OK：
    出勤 09:00、退勤 18:00

    NG：
    出勤 18:00、退勤 09:00
    */
    CONSTRAINT ck_attendances_clock_order
        CHECK (
            clock_out_at IS NULL
            OR clock_in_at IS NULL
            OR clock_out_at >= clock_in_at
        )
);


/*
=====================================================
attendance_correction_requests テーブル

利用者が、間違った出勤時刻・退勤時刻・
休憩時間の修正を申請するためのテーブル。

修正前と修正後の情報を両方保存することで、
「何をどのように変更したかったのか」を
後から確認できる。

管理者は申請内容を確認して、
承認または却下する。
=====================================================
*/
CREATE TABLE attendance_correction_requests (

    /*
    打刻修正申請ID（主キー）

    修正申請を1件ずつ識別するための番号。
    PostgreSQLが自動で番号を付ける。
    */
    correction_request_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    /*
    勤怠ID（外部キー）

    どの勤怠データを修正したいのかを表す。

    attendancesテーブルの
    attendance_idにつながる。
    */
    attendance_id BIGINT
        NOT NULL,

    /*
    ユーザーID（外部キー）

    誰が修正申請を行ったのかを表す。

    usersテーブルのuser_idにつながる。
    */
    user_id BIGINT
        NOT NULL,

    /*
    修正前出勤日時

    修正申請を出した時点の出勤日時を保存する。

    出勤打刻自体が存在しない場合も考えられるため、
    NULLを許可している。
    */
    original_clock_in_at TIMESTAMP,

    /*
    修正前退勤日時

    修正申請を出した時点の退勤日時を保存する。

    退勤打刻が存在しない場合も考えられるため、
    NULLを許可している。
    */
    original_clock_out_at TIMESTAMP,

    /*
    修正前休憩時間（分）

    修正申請を出した時点の休憩時間を保存する。

    値がない場合は0分として扱う。
    */
    original_break_minutes INTEGER
        NOT NULL
        DEFAULT 0,

    /*
    修正後出勤日時

    利用者が希望する、正しい出勤日時を保存する。

    出勤日時を変更しない申請も考えられるため、
    NULLを許可している。
    */
    corrected_clock_in_at TIMESTAMP,

    /*
    修正後退勤日時

    利用者が希望する、正しい退勤日時を保存する。

    退勤日時を変更しない申請も考えられるため、
    NULLを許可している。
    */
    corrected_clock_out_at TIMESTAMP,

    /*
    修正後休憩時間（分）

    利用者が希望する、正しい休憩時間を保存する。

    値が指定されていない場合は0分になる。
    */
    corrected_break_minutes INTEGER
        NOT NULL
        DEFAULT 0,

    /*
    修正理由

    なぜ打刻を修正する必要があるのかを保存する。

    例：
    ・出勤ボタンを押し忘れた
    ・退勤時刻を間違えて登録した
    ・休憩時間を入力し忘れた

    修正理由は必須。
    */
    correction_reason VARCHAR(255)
        NOT NULL,

    /*
    申請状態

    修正申請が現在どの状態なのかを保存する。

    PENDING ：申請中
    APPROVED：承認
    REJECTED：却下
    CANCELED：取消

    新規申請時の初期値はPENDING。
    */
    status VARCHAR(20)
        NOT NULL
        DEFAULT 'PENDING',

    /*
    管理者コメント

    管理者が承認または却下するときに、
    コメントを保存する。

    入力しない場合もあるため、NULLを許可している。
    */
    admin_comment VARCHAR(255),

    /*
    処理管理者ID（外部キー）

    どの管理者が承認または却下したかを保存する。

    申請中はまだ処理されていないため、
    NULLを許可している。

    usersテーブルのuser_idにつながる。
    */
    processed_by BIGINT,

    /*
    処理日時

    管理者が承認または却下した日時を保存する。

    申請中はまだ処理されていないため、
    NULLを許可している。
    */
    processed_at TIMESTAMP,

    /*
    作成日時

    利用者が修正申請を作成した日時。
    INSERT時に現在日時が自動で保存される。
    */
    created_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    /*
    更新日時

    申請内容や申請状態を最後に更新した日時。

    更新時はJava側で現在日時を設定する。
    */
    updated_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,


    /*
    =====================================================
    ここからattendance_correction_requestsの制約
    =====================================================
    */

    /*
    correction_request_idを主キーに設定する。
    */
    CONSTRAINT pk_attendance_correction_requests
        PRIMARY KEY (correction_request_id),

    /*
    attendance_idを外部キーに設定する。

    attendancesテーブルに存在する勤怠データだけを
    修正申請の対象にできる。
    */
    CONSTRAINT fk_correction_requests_attendance
        FOREIGN KEY (attendance_id)
        REFERENCES attendances (attendance_id)
        ON DELETE RESTRICT,

    /*
    申請者のuser_idを外部キーに設定する。

    usersテーブルに存在する利用者だけが
    修正申請者として登録できる。
    */
    CONSTRAINT fk_correction_requests_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE RESTRICT,

    /*
    処理管理者IDを外部キーに設定する。

    管理者ユーザーが削除された場合でも、
    修正申請そのものは残す。

    その場合、processed_byだけをNULLにする。
    */
    CONSTRAINT fk_correction_requests_processed_by
        FOREIGN KEY (processed_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,

    /*
    修正前休憩時間にマイナス値が入ることを禁止する。
    */
    CONSTRAINT ck_correction_original_break_minutes
        CHECK (original_break_minutes >= 0),

    /*
    修正後休憩時間にマイナス値が入ることを禁止する。
    */
    CONSTRAINT ck_correction_corrected_break_minutes
        CHECK (corrected_break_minutes >= 0),

    /*
    statusに登録できる値を4種類に制限する。

    ・PENDING
    ・APPROVED
    ・REJECTED
    ・CANCELED
    */
    CONSTRAINT ck_correction_requests_status
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'CANCELED'
            )
        ),

    /*
    修正前の退勤日時が、
    修正前の出勤日時より前になることを禁止する。

    どちらかがNULLの場合はエラーにしない。
    */
    CONSTRAINT ck_correction_original_clock_order
        CHECK (
            original_clock_out_at IS NULL
            OR original_clock_in_at IS NULL
            OR original_clock_out_at >= original_clock_in_at
        ),

    /*
    修正後の退勤日時が、
    修正後の出勤日時より前になることを禁止する。

    どちらかがNULLの場合はエラーにしない。
    */
    CONSTRAINT ck_correction_corrected_clock_order
        CHECK (
            corrected_clock_out_at IS NULL
            OR corrected_clock_in_at IS NULL
            OR corrected_clock_out_at >= corrected_clock_in_at
        )
);

/*
=====================================================
shift_requests テーブル

利用者が希望する勤務日・出勤予定時刻・
退勤予定時刻などを申請するためのテーブル。

管理者は申請内容を確認して、
承認または却下する。
=====================================================
*/
CREATE TABLE shift_requests (

    /*
    シフト申請ID（主キー）

    シフト申請を1件ずつ識別するための番号。
    PostgreSQLが自動で番号を付ける。
    */
    shift_request_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    /*
    ユーザーID（外部キー）

    誰がシフト申請を行ったのかを表す。

    usersテーブルのuser_idにつながる。
    */
    user_id BIGINT
        NOT NULL,

    /*
    勤務希望日

    利用者が勤務を希望する日付を保存する。

    保存例：
    2026-08-10
    */
    work_date DATE
        NOT NULL,

    /*
    出勤予定時刻

    利用者が希望する出勤時刻を保存する。

    TIME型なので、日付は含まない。

    保存例：
    09:00:00
    */
    planned_clock_in_time TIME
        NOT NULL,

    /*
    退勤予定時刻

    利用者が希望する退勤時刻を保存する。

    保存例：
    18:00:00
    */
    planned_clock_out_time TIME
        NOT NULL,

    /*
    休憩予定時間（分）

    予定している休憩時間を分単位で保存する。

    例：
    60分休憩 → 60
    90分休憩 → 90

    値を省略した場合は0が入る。
    */
    planned_break_minutes INTEGER
        NOT NULL
        DEFAULT 0,

    /*
    申請備考

    利用者がシフト申請に関する
    補足情報を入力する。

    入力しない場合もあるため、NULLを許可している。
    */
    request_note VARCHAR(255),

    /*
    申請状態

    PENDING ：申請中
    APPROVED：承認
    REJECTED：却下
    CANCELED：取消

    新規申請時の初期値はPENDING。
    */
    status VARCHAR(20)
        NOT NULL
        DEFAULT 'PENDING',

    /*
    管理者コメント

    管理者が承認・却下するときの
    コメントを保存する。

    入力しない場合もあるため、NULLを許可している。
    */
    admin_comment VARCHAR(255),

    /*
    処理管理者ID（外部キー）

    どの管理者が承認または却下したかを保存する。

    申請中はまだ管理者が処理していないため、
    NULLを許可している。
    */
    processed_by BIGINT,

    /*
    処理日時

    管理者が承認または却下した日時を保存する。

    申請中はNULL。
    */
    processed_at TIMESTAMP,

    /*
    作成日時

    シフト申請を登録した日時。
    新規登録時に現在日時が自動で入る。
    */
    created_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    /*
    更新日時

    シフト申請を最後に更新した日時。

    更新時はJava側で現在日時を設定する。
    */
    updated_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,


    /*
    =====================================================
    ここからshift_requestsテーブルの制約
    =====================================================
    */

    /*
    shift_request_idを主キーに設定する。
    */
    CONSTRAINT pk_shift_requests
        PRIMARY KEY (shift_request_id),

    /*
    user_idを外部キーに設定する。

    usersテーブルに存在する利用者だけが
    シフト申請者として登録できる。
    */
    CONSTRAINT fk_shift_requests_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE RESTRICT,

    /*
    processed_byを外部キーに設定する。

    処理した管理者が削除された場合でも、
    シフト申請の記録は残す。

    その場合はprocessed_byだけNULLになる。
    */
    CONSTRAINT fk_shift_requests_processed_by
        FOREIGN KEY (processed_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,

    /*
    休憩予定時間にマイナス値が
    入ることを禁止する。
    */
    CONSTRAINT ck_shift_requests_break_minutes
        CHECK (planned_break_minutes >= 0),

    /*
    退勤予定時刻が出勤予定時刻より
    後になるように制限する。

    今回は日付をまたぐ勤務を許可しない前提。
    */
    CONSTRAINT ck_shift_requests_time_order
        CHECK (
            planned_clock_out_time
            > planned_clock_in_time
        ),

    /*
    statusに登録できる値を4種類に制限する。
    */
    CONSTRAINT ck_shift_requests_status
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'CANCELED'
            )
        )
);


/*
=====================================================
paid_leave_requests テーブル

利用者が有給休暇を申請するためのテーブル。

全日休暇・午前休・午後休を管理する。

管理者は申請内容を確認して、
承認または却下する。
=====================================================
*/
CREATE TABLE paid_leave_requests (

    /*
    有給申請ID（主キー）

    有給申請を1件ずつ識別するための番号。
    PostgreSQLが自動で番号を付ける。
    */
    paid_leave_request_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    /*
    ユーザーID（外部キー）

    誰が有給申請を行ったのかを表す。
    */
    user_id BIGINT
        NOT NULL,

    /*
    有給取得日

    有給休暇を取得したい日付を保存する。

    保存例：
    2026-08-15
    */
    leave_date DATE
        NOT NULL,

    /*
    有給区分

    FULL_DAY：全日休
    AM_HALF ：午前休
    PM_HALF ：午後休

    初期値はFULL_DAY。
    */
    leave_type VARCHAR(20)
        NOT NULL
        DEFAULT 'FULL_DAY',

    /*
    申請理由

    有給休暇を申請する理由を保存する。

    有給理由を必須にしない会社もあるため、
    今回はNULLを許可している。
    */
    reason VARCHAR(255),

    /*
    取得日数

    全日休の場合は1.0日、
    午前休・午後休の場合は0.5日を保存する。

    NUMERIC(3,1)は、
    小数点を含めて最大3桁、
    小数部分は1桁という意味。

    保存例：
    1.0
    0.5
    */
    requested_days NUMERIC(3,1)
        NOT NULL
        DEFAULT 1.0,

    /*
    申請状態

    PENDING ：申請中
    APPROVED：承認
    REJECTED：却下
    CANCELED：取消
    */
    status VARCHAR(20)
        NOT NULL
        DEFAULT 'PENDING',

    /*
    管理者コメント

    管理者が承認・却下するときの
    コメントを保存する。
    */
    admin_comment VARCHAR(255),

    /*
    処理管理者ID（外部キー）

    どの管理者が処理したかを保存する。

    申請中はNULL。
    */
    processed_by BIGINT,

    /*
    処理日時

    管理者が承認または却下した日時。
    */
    processed_at TIMESTAMP,

    /*
    作成日時

    有給申請を作成した日時。
    */
    created_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    /*
    更新日時

    有給申請を最後に更新した日時。
    */
    updated_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,


    /*
    =====================================================
    ここからpaid_leave_requestsテーブルの制約
    =====================================================
    */

    /*
    paid_leave_request_idを主キーに設定する。
    */
    CONSTRAINT pk_paid_leave_requests
        PRIMARY KEY (paid_leave_request_id),

    /*
    user_idを外部キーに設定する。
    */
    CONSTRAINT fk_paid_leave_requests_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE RESTRICT,

    /*
    processed_byを外部キーに設定する。

    管理者が削除されても、
    有給申請の記録は残す。
    */
    CONSTRAINT fk_paid_leave_requests_processed_by
        FOREIGN KEY (processed_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,

    /*
    leave_typeに登録できる値を
    3種類に制限する。
    */
    CONSTRAINT ck_paid_leave_requests_type
        CHECK (
            leave_type IN (
                'FULL_DAY',
                'AM_HALF',
                'PM_HALF'
            )
        ),

    /*
    取得日数は0より大きい値だけを許可する。
    */
    CONSTRAINT ck_paid_leave_requests_days_positive
        CHECK (requested_days > 0),

    /*
    有給区分と取得日数の組み合わせを制限する。

    FULL_DAYの場合は1.0日、
    AM_HALF・PM_HALFの場合は0.5日。
    */
    CONSTRAINT ck_paid_leave_requests_days_match
        CHECK (
            (
                leave_type = 'FULL_DAY'
                AND requested_days = 1.0
            )
            OR
            (
                leave_type IN ('AM_HALF', 'PM_HALF')
                AND requested_days = 0.5
            )
        ),

    /*
    statusに登録できる値を4種類に制限する。
    */
    CONSTRAINT ck_paid_leave_requests_status
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'CANCELED'
            )
        )
);


/*
=====================================================
overtime_requests テーブル

利用者が残業予定日・開始予定時刻・
終了予定時刻などを申請するためのテーブル。

管理者は申請内容を確認して、
承認または却下する。
=====================================================
*/
CREATE TABLE overtime_requests (

    /*
    残業申請ID（主キー）

    残業申請を1件ずつ識別するための番号。
    */
    overtime_request_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    /*
    ユーザーID（外部キー）

    誰が残業申請を行ったのかを表す。
    */
    user_id BIGINT
        NOT NULL,

    /*
    残業予定日

    残業を行う予定の日付を保存する。
    */
    overtime_date DATE
        NOT NULL,

    /*
    残業開始予定時刻

    残業を開始する予定の時刻を保存する。

    保存例：
    18:00:00
    */
    start_time TIME
        NOT NULL,

    /*
    残業終了予定時刻

    残業を終了する予定の時刻を保存する。

    保存例：
    20:00:00
    */
    end_time TIME
        NOT NULL,

    /*
    残業予定時間（分）

    開始予定時刻と終了予定時刻の差を
    分単位で保存する。

    例：
    18:00～20:00 → 120分
    */
    overtime_minutes INTEGER
        NOT NULL,

    /*
    申請理由

    なぜ残業が必要なのかを保存する。

    残業申請では理由を必須にする。
    */
    reason VARCHAR(255)
        NOT NULL,

    /*
    申請状態

    PENDING ：申請中
    APPROVED：承認
    REJECTED：却下
    CANCELED：取消
    */
    status VARCHAR(20)
        NOT NULL
        DEFAULT 'PENDING',

    /*
    管理者コメント

    承認・却下時のコメントを保存する。
    */
    admin_comment VARCHAR(255),

    /*
    処理管理者ID（外部キー）

    どの管理者が申請を処理したかを保存する。
    */
    processed_by BIGINT,

    /*
    処理日時

    管理者が承認または却下した日時。
    */
    processed_at TIMESTAMP,

    /*
    作成日時

    残業申請を登録した日時。
    */
    created_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    /*
    更新日時

    残業申請を最後に更新した日時。
    */
    updated_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,


    /*
    =====================================================
    ここからovertime_requestsテーブルの制約
    =====================================================
    */

    /*
    overtime_request_idを主キーに設定する。
    */
    CONSTRAINT pk_overtime_requests
        PRIMARY KEY (overtime_request_id),

    /*
    user_idを外部キーに設定する。
    */
    CONSTRAINT fk_overtime_requests_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE RESTRICT,

    /*
    processed_byを外部キーに設定する。
    */
    CONSTRAINT fk_overtime_requests_processed_by
        FOREIGN KEY (processed_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,

    /*
    残業終了予定時刻が、
    残業開始予定時刻より後になるように制限する。

    今回は日付をまたぐ残業を許可しない前提。
    */
    CONSTRAINT ck_overtime_requests_time_order
        CHECK (end_time > start_time),

    /*
    残業予定時間にマイナス値や0が
    入ることを禁止する。
    */
    CONSTRAINT ck_overtime_requests_minutes_positive
        CHECK (overtime_minutes > 0),

    /*
    残業予定時間を30分単位に制限する。

    30、60、90、120などは登録できる。
    45、75などは登録できない。
    */
    CONSTRAINT ck_overtime_requests_minutes_unit
        CHECK (overtime_minutes % 30 = 0),

    /*
    statusに登録できる値を4種類に制限する。
    */
    CONSTRAINT ck_overtime_requests_status
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'CANCELED'
            )
        )
);


/*
=====================================================
transportation_expense_requests テーブル

利用者が日ごとの交通費または
定期券代を申請するためのテーブル。

交通費区分によって、
必要となる入力項目が変わる。

DAILY        ：日ごとの交通費
COMMUTER_PASS：定期券
=====================================================
*/
CREATE TABLE transportation_expense_requests (

    /*
    交通費申請ID（主キー）

    交通費申請を1件ずつ識別するための番号。
    */
    transportation_expense_request_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,

    /*
    ユーザーID（外部キー）

    誰が交通費申請を行ったのかを表す。
    */
    user_id BIGINT
        NOT NULL,

    /*
    交通費区分

    DAILY        ：日ごとの交通費
    COMMUTER_PASS：定期券

    初期値はDAILY。
    */
    expense_type VARCHAR(20)
        NOT NULL
        DEFAULT 'DAILY',

    /*
    利用日

    日ごとの交通費を利用した日付を保存する。

    定期券申請では使用しないため、
    NULLを許可している。
    */
    usage_date DATE,

    /*
    出発駅

    利用区間の出発駅を保存する。

    例：
    名古屋駅
    金山駅
    */
    start_station VARCHAR(100)
        NOT NULL,

    /*
    到着駅

    利用区間の到着駅を保存する。
    */
    end_station VARCHAR(100)
        NOT NULL,

    /*
    交通手段

    TRAIN：電車
    BUS  ：バス
    TAXI ：タクシー
    OTHER：その他

    初期値はTRAIN。
    */
    transportation_method VARCHAR(30)
        NOT NULL
        DEFAULT 'TRAIN',

    /*
    申請金額

    交通費として申請する金額を保存する。

    NUMERIC(10,0)は、
    最大10桁の整数を保存できるという意味。

    保存例：
    240
    12800
    */
    amount NUMERIC(10,0)
        NOT NULL,

    /*
    定期券開始日

    定期券の利用開始日を保存する。

    日ごとの交通費申請では使用しないため、
    NULLを許可している。
    */
    pass_start_date DATE,

    /*
    定期券月数

    定期券の期間を月数で保存する。

    1か月、2か月、3か月のいずれか。

    日ごとの交通費申請ではNULL。
    */
    pass_months INTEGER,

    /*
    利用目的

    交通費を利用した目的を保存する。

    例：
    ・通勤
    ・研修参加
    ・顧客先訪問
    */
    purpose VARCHAR(255)
        NOT NULL,

    /*
    申請状態

    PENDING ：申請中
    APPROVED：承認
    REJECTED：却下
    CANCELED：取消
    */
    status VARCHAR(20)
        NOT NULL
        DEFAULT 'PENDING',

    /*
    管理者コメント

    承認・却下時のコメントを保存する。
    */
    admin_comment VARCHAR(255),

    /*
    処理管理者ID（外部キー）

    どの管理者が申請を処理したかを保存する。
    */
    processed_by BIGINT,

    /*
    処理日時

    管理者が承認または却下した日時。
    */
    processed_at TIMESTAMP,

    /*
    作成日時

    交通費申請を作成した日時。
    */
    created_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    /*
    更新日時

    交通費申請を最後に更新した日時。
    */
    updated_at TIMESTAMP
        NOT NULL
        DEFAULT CURRENT_TIMESTAMP,


    /*
    =====================================================
    ここからtransportation_expense_requestsの制約
    =====================================================
    */

    /*
    transportation_expense_request_idを
    主キーに設定する。
    */
    CONSTRAINT pk_transportation_expense_requests
        PRIMARY KEY (
            transportation_expense_request_id
        ),

    /*
    user_idを外部キーに設定する。
    */
    CONSTRAINT fk_transportation_requests_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE RESTRICT,

    /*
    processed_byを外部キーに設定する。
    */
    CONSTRAINT fk_transportation_requests_processed_by
        FOREIGN KEY (processed_by)
        REFERENCES users (user_id)
        ON DELETE SET NULL,

    /*
    expense_typeに登録できる値を
    2種類に制限する。
    */
    CONSTRAINT ck_transportation_requests_type
        CHECK (
            expense_type IN (
                'DAILY',
                'COMMUTER_PASS'
            )
        ),

    /*
    交通手段に登録できる値を
    4種類に制限する。
    */
    CONSTRAINT ck_transportation_requests_method
        CHECK (
            transportation_method IN (
                'TRAIN',
                'BUS',
                'TAXI',
                'OTHER'
            )
        ),

    /*
    申請金額が0以下になることを禁止する。
    */
    CONSTRAINT ck_transportation_requests_amount
        CHECK (amount > 0),

    /*
    出発駅と到着駅が同じになることを禁止する。

    例：
    名古屋駅 → 名古屋駅
    のような申請は登録できない。
    */
    CONSTRAINT ck_transportation_requests_station
        CHECK (start_station <> end_station),

    /*
    交通費区分ごとの必須項目を制限する。

    DAILYの場合：
    ・usage_dateが必須
    ・pass_start_dateはNULL
    ・pass_monthsはNULL

    COMMUTER_PASSの場合：
    ・usage_dateはNULL
    ・pass_start_dateが必須
    ・pass_monthsが必須
    */
    CONSTRAINT ck_transportation_requests_details
        CHECK (
            (
                expense_type = 'DAILY'
                AND usage_date IS NOT NULL
                AND pass_start_date IS NULL
                AND pass_months IS NULL
            )
            OR
            (
                expense_type = 'COMMUTER_PASS'
                AND usage_date IS NULL
                AND pass_start_date IS NOT NULL
                AND pass_months IS NOT NULL
            )
        ),

    /*
    定期券月数は1、2、3のいずれかにする。

    日ごとの交通費申請ではNULLを許可する。
    */
    CONSTRAINT ck_transportation_requests_pass_months
        CHECK (
            pass_months IS NULL
            OR pass_months IN (1, 2, 3)
        ),

    /*
    statusに登録できる値を4種類に制限する。
    */
    CONSTRAINT ck_transportation_requests_status
        CHECK (
            status IN (
                'PENDING',
                'APPROVED',
                'REJECTED',
                'CANCELED'
            )
        )
);